services:
  # Integration Server
  # https://www.ibm.com/docs/en/webmethods-integration/wm-integration-server/11.1.0?topic=ev-environment-variables-defined-in-integration-server-microservices-runtime
  is:
    # image: ibmwebmethods.azurecr.io/webmethods-microservicesruntime:11.1
    image: webmethods-microservicesruntime:11.1
    build:
      context: is
      dockerfile: Dockerfile
      args:
        - BASE_IMAGE=ibmwebmethods.azurecr.io/webmethods-microservicesruntime:11.1
        - WPM_TOKEN
    hostname: is
    ports:
      - "5555:5555"
      - "5543:5543"
    environment:
      - JAVA_MIN_MEM=512m
      - JAVA_MAX_MEM=512m
      - SAG_IS_ADMIN_PASSWORD=manage
      - SAG_IS_DEBUG_LEVEL=Info
    volumes:
      - './is/IntegrationServer/application.properties:/opt/softwareag/IntegrationServer/application.properties'
    stop_grace_period: 30s

  # Universal Messaging
  # https://www.ibm.com/docs/en/webmethods-integration/wm-universal-messaging/11.1.0?topic=containers-running-universal-messaging
  um:
    image: ibmwebmethods.azurecr.io/universalmessaging-server:11.1
    hostname: um
    ports:
      - "9000:9000"
    environment:
      - INIT_JAVA_MEM_SIZE=512
      - MAX_JAVA_MEM_SIZE=512
    volumes:
      - 'um-data:/opt/softwareag/UniversalMessaging/server/default/data'
    stop_grace_period: 30s

  # API Gateway
  # https://www.ibm.com/docs/en/wam/wm-api-gateway/11.1.0?topic=deployment-how-install-webmethods-api-gateway-using-docker
  # https://www.ibm.com/docs/en/wam/wm-api-gateway/11.1.0?topic=configurations-using-externalized-configuration-files
  apigw:
    image: ibmwebmethods.azurecr.io/apigateway-minimal:11.1
    hostname: apigw
    ports:
      - "5556:5555"
      - "9072:9072"
    environment:
      - apigw_aliases_is_connectionTimeout=30
      - apigw_aliases_is_endPointURI=http://is:5555
      - apigw_aliases_is_passSecurityHeaders=true
      - apigw_aliases_is_readTimeout=30
      - apigw_aliases_is_type=endpoint
      - apigw_elasticsearch_hosts=apigw-es:9200
      - apigw_kibana_dashboardInstance=http://apigw-kb:5601
      - apigw_wrapper_java_initmemory=512
      - apigw_wrapper_java_maxmemory=512
      - APIGW_UNAUTHENTICATED_HEALTH_CHECK=true
      - SAG_IS_ADMIN_PASSWORD=manage
      - SAG_IS_DEBUG_LEVEL=Info
    volumes:
      - './apigw/IntegrationServer/application.properties:/opt/softwareag/IntegrationServer/application.properties'
    stop_grace_period: 30s

  apigw-es:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.3
    hostname: apigw-es
    environment:
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - discovery.type=single-node
      - xpack.security.enabled=false
    volumes:
      - apigw-es-data:/usr/share/elasticsearch/data

  apigw-kb:
    image: docker.elastic.co/kibana/kibana:8.17.3
    hostname: apigw-kb
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://apigw-es:9200
      - SERVER_BASEPATH=/apigatewayui/dashboardproxy
      - TELEMETRY_OPTIN=false

  # Microgateway
  # https://www.ibm.com/docs/en/wam/webmethods-microgateway/11.1.0?topic=provisioning-microgateway-docker-environment-variables
  mcgw:
    image: ibmwebmethods.azurecr.io/microgateway:11.1
    hostname: mcgw
    ports:
      - "4485:4485"
    environment:
      - mcgw_ports_http=4485
      - mcgw_api_gateway_url=apigw:5555
      - mcgw_api_gateway_user=Administrator
      - mcgw_api_gateway_password=manage
      - mcgw_downloads_apis=petstore

  # Developer Portal
  # https://www.ibm.com/docs/en/wam/wdp/11.1.0?topic=started-installing-stand-alone-developer-portal-using-docker
  devportal:
    image: ibmwebmethods.azurecr.io/devportal:11.1
    hostname: devportal
    ports:
      - "18101:8080"
      - "18102:8443"
    environment:
      - SPRING_ELASTICSEARCH_URIS=http://devportal-es:9200

  devportal-es:
    image: opensearchproject/opensearch:2.19.1
    hostname: devportal-es
    environment:
      - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m
      - DISABLE_SECURITY_PLUGIN=true
      - discovery.type=single-node
    volumes:
      - devportal-es-data:/usr/share/opensearch/data

  # Active Transfer
  # https://www.ibm.com/docs/en/webmethods-activetransfer/11.1.0?topic=server-using-activetransfer-docker
  mft:
    image: ibmwebmethods.azurecr.io/webmethods-activetransfer:11.1
    hostname: mft
    ports:
      - "5557:5555"
      - "5558:5558"
      - "2222:2222"
    environment:
      - JAVA_MIN_MEM=512m
      - JAVA_MAX_MEM=512m
      - SAG_IS_ADMIN_PASSWORD=manage
      - SAG_IS_DEBUG_LEVEL=Info
    volumes:
      - ./mft/IntegrationServer/application.properties:/opt/softwareag/IntegrationServer/application.properties
    stop_grace_period: 30s

  mft-pg:
    image: postgres:15
    hostname: mft-pg
    environment:
      - POSTGRES_USER=mft
      - POSTGRES_PASSWORD=mft
      - POSTGRES_DB=mft
    volumes:
      - mft-pg-data:/var/lib/postgresql/data

  mft-dcc:
    image: ibmwebmethods.azurecr.io/webmethods-activetransfer-dcc:11.1
    hostname: mft-dcc
    environment:
      - DB_ACTION=create
    volumes:
      - ./mft/db:/opt/softwareag/common/auth/db:ro
    profiles:
      - mft-dcc

volumes:
  um-data:
  apigw-es-data:
  devportal-es-data:
  mft-pg-data:
