# Configuration Variables Template
# https://www.ibm.com/docs/en/webmethods-integration/wm-integration-server/11.1.0?topic=guide-configuration-variables-template-assets

# JDBC pools
jdbc.DBPool.dbURL=jdbc:wm:postgresql://mft-pg:5432;databaseName=mft
jdbc.DBPool.userid=mft
jdbc.DBPool.password=mft
jdbc.DBPool.driverAlias=DataDirect Connect JDBC PostgreSQL Driver
jdbc.DBPool.minConns=1
jdbc.DBPool.maxConns=10
jdbc.DBPoolArchive.dbURL=jdbc:wm:postgresql://mft-pg:5432;databaseName=mft
jdbc.DBPoolArchive.userid=mft
jdbc.DBPoolArchive.password=mft
jdbc.DBPoolArchive.driverAlias=DataDirect Connect JDBC PostgreSQL Driver
jdbc.DBPoolArchive.minConns=1
jdbc.DBPoolArchive.maxConns=10
jdbcfunc.ISInternal.connPoolAlias=DBPool
jdbcfunc.ISCoreAudit.connPoolAlias=DBPool
jdbcfunc.ActiveTransfer.connPoolAlias=DBPool
jdbcfunc.ActiveTransferArchive.connPoolAlias=DBPoolArchive  
jdbcfunc.CentralUsers.connPoolAlias=DBPool

# Extended Settings
# https://www.ibm.com/docs/en/webmethods-integration/wm-integration-server/11.1.0?topic=guide-server-configuration-parameters
settings.watt.net.timeout=60
settings.watt.server.audit.logFilesToKeep=7
settings.watt.server.audit.logRotateSize=20MB
settings.watt.server.clientTimeout=5
settings.watt.server.dateStampFmt=yyyy-MM-dd HH:mm:ss.SSSXXX
settings.watt.server.diagnostic.threadDumper=false
settings.watt.server.http.returnException=false
settings.watt.server.log.alertMaxEntries=5000
settings.watt.server.log.maxEntries=500
settings.watt.server.math.floatOperation.mode=dynamic
settings.watt.server.ns.hideWmRoot=false
settings.watt.server.serverlogFilesToKeep=7
settings.watt.server.serverlogRotateSize=20MB
settings.watt.server.stats.logFilesToKeep=7
settings.watt.server.stats.logRotateSize=20MB
settings.watt.server.threadKill.interruptThread.enabled=true
settings.watt.server.threadPool=500
